config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments, only: [:create, :edit, :destroy, :update]
    resources :gossip_likes, only: [:create, :destroy]
  end

  resources :users, only: [:show, :create, :new]
  root to: redirect('/gossips')
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  get '/welcome/:first_name', to: 'welcome#show'
  get '/welcome', to: 'welcome#index'
  get '/contact', to: 'contact#index'
  get '/team', to: 'team#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comment_likes
  belongs_to :user
  belongs_to :gossip
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :child_comments, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14}
  validates :content,
    presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :comment_likes
  has_many :gossip_likes
  has_many :comments
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]
  before_action :authenticate_author, only: [:edit, :update, :destroy]

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossip = Gossip.includes(:user)
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossip.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    @gossip = Gossip.new(title: params['title'], content: params['content'], user: current_user)
      if @gossip.save
      flash[:notice] = 'Le gossip a bien été créé'
      redirect_to root_path
      else
      flash[:alert] = @gossip.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(post_params)
      flash[:notice] = 'Le gossip a bien été mis à jour'
      redirect_to gossip_path
      else
      flash[:alert] = @gossip.errors.full_messages[0]
      render 'edit'
    end 
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
      flash[:notice] = 'Le gossip a bien été supprimé'
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter !"
      redirect_to new_session_path
    end
  end

  def authenticate_author
    unless current_user == Gossip.find(params[:id]).user
      flash[:alert] = "Vous n'êtes pas l'auteur !"
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params['first_name'], last_name: params['last_name'], description: params['description'], email: params['email'], age: params['age'], city_id: City.all.sample.id, password: params['password'], password_confirmation: params['password_confirmation'])
      if @user.save
      flash[:notice] = 'Inscription validée'
      redirect_to root_path
      else
      flash[:alert] = @user.errors.full_messages[0]
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_likes_helper.rb
module GossipLikesHelper
  def already_exist?(gossip)
    GossipLike.where(user: current_user, gossip_id: gossip.id).length > 0
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h1> Edition du potin</h1>

<%= form_for @gossip do |f| %>

  <div class="form-group">
    <label>Titre du gossip</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Contenu du gossip</label>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
<br>
  <div class="form-group" data-turbo=false>
    <button type="submit">Modifier le potin</button>
  </div>

  <% end %>

app/views/gossips/index.html.erb
<div class="text-center">
<br>
<h1><b>Bienvenue sur The Gossip Project !</b></h1>
<br>
<h2> Voici la liste des potins : </h2>
<br>
</div>
<div class="card-container">
  <style>
    .avatar-image {
      border-radius: 50%;
    }
  </style>
  <% @gossip.reverse_each do |gossip| %>
    <div class="card">
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
            <% avatar_id = gossip.user.id %>
            <% avatar_url = "https://i.pravatar.cc/150?u=#{avatar_id}" %>
            <img src="<%= avatar_url %>" class="avatar-image" height="65" width="65" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <h2><%= gossip.title %></h2>
          <p>par : <%= link_to gossip.user.first_name, user_path(gossip.user), class: 'highlight' %><br>
             de : <%= link_to gossip.user.city.name, city_path(gossip.user.city), class: 'highlight'%></p>
          <p><%= link_to 'Voir détails', gossip_path(gossip) %></p>
                        <%if already_exist?(gossip)%>
                          <%= link_to "♥", gossip_gossip_like_path(gossip_id: gossip.id, id: current_user.id), data: { turbo_method: :delete } %>
                            <%else%>
                          <%= link_to "♡", gossip_gossip_likes_url(gossip.id), data: { turbo_method: :post } %>
                        <%end%>
                        <%= gossip.gossip_likes.count %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<center>
<br>
    <%= form_tag('/gossips', method: :post) do %>

      <%= label_tag 'Titre du potin' %></br>
        <div><%= text_field_tag 'title' %>
      <br/> <br/>

      <%= label_tag 'à toi de jouer !' %></br>
        </div><%= text_area_tag 'content' %></div>
      <br/> <br/>

      <%= submit_tag "Ajouter un nouveau potin", :class=>"btn btn-dark", data: {turbo:false} %>

      <% end %>

    </center>

app/views/gossips/show.html.erb
    <center>
    <br>
    <p>Auteur : <%=@gossip.user.first_name%> <%=@gossip.user.last_name%><br>
    (tu veux en savoir plus sur l'auteur ? clique <%= link_to 'ici', user_path(@gossip.user) %>)</p>
    <p>Ville : <%= @gossip.user.city.name %></p>
    <p>Title : <%= @gossip.title %></p>
    <p>Content : <%= @gossip.content %></p>
    <p>Date de création : <%= @gossip.created_at.strftime('%d/%m/%Y') %></p>
    <% if @gossip.user == current_user %>
    <%= button_to "Editer ce potin", edit_gossip_path, :class=>"btn btn-dark", method: :get %>
    <%= button_to "Supprimer ce potin", gossip_path(@gossip.id), :class=>"btn btn-dark", form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>
    <% end %>
    <br>
    <br>
    <%= form_tag(gossip_comments_path(@gossip), method: :post) do %>
        <br>
          <%= text_area_tag :content, nil, placeholder: "Votre commentaire", rows: 3, cols: 50 %>
        <br/>
        <%= submit_tag "Ajoute ton commentaire",:class=>"btn btn-dark", data: {turbo:false} %>
        <% end %>
    <br>
        <% @gossip.comments.reverse_each do |comment| %>
            <div><%= comment.user.first_name %> <%= comment.user.last_name %> - <%= comment.content %>
            <% if comment.user == current_user %> <%= button_to "Editer", edit_gossip_comment_path(@gossip, comment.id), :class=>"btn btn-dark", method: :get %> </div>
            <% end %>
          <% end %>
    </center>