config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments, only: [:create, :edit, :destroy, :update]
    resources :gossip_likes, only: [:create, :destroy]
  end

  resources :users, only: [:show, :create, :new]
  root to: redirect('/gossips')
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]

  get '/welcome/:first_name', to: 'welcome#show'
  get '/welcome', to: 'welcome#index'
  get '/contact', to: 'contact#index'
  get '/team', to: 'team#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comment_likes
  belongs_to :user
  belongs_to :gossip
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :child_comments, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14}
  validates :content,
    presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :comment_likes
  has_many :gossip_likes
  has_many :comments
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGossipProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css', integrity: 'sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ', crossorigin: 'anonymous' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <!-- ... autres balises ... -->
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js', integrity: 'sha384-...', crossorigin: 'anonymous', defer: true %>
  <!-- Ajoutez les balises script et link de Bootstrap ici -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid">
  <%= link_to "The Gossip Project", root_path, class:"nav-item nav-link text-danger" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Contact", contact_path, class:"nav-item nav-link active" %>
      <%= link_to "Team", team_path, class:"nav-item nav-link active" %>
      <%= link_to "Créer un potin", new_gossip_path, class:"nav-item nav-link active" %>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if current_user %>
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" role="button" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.first_name %> <%= current_user.last_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
              <%= button_to "Se déconnecter", session_path(session.id), form: { data: { turbo_confirm: "Veux-tu te déconnecter ?" } }, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" role="button" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              S'inscrire / Se connecter
            </a>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
              <%= link_to "S'inscrire", new_user_path, class: "dropdown-item" %>
              <%= link_to "Se connecter", new_session_path, class: "dropdown-item" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>
</header>


<% if notice %>
      <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>


  <body>
    <%= yield %>
  </body>
</html>